export const CHALLENGES_FETCHED = 'CHALLENGES_FETCHED';
export const CHALLENGE_FETCH_FAILED = 'CHALLENGE_FETCH_FAILED';
export const CHALLENGE_CREATED = 'CHALLENGE_CREATED';
export const CHALLENGE_CREATE_FAILED = 'CHALLENGE_CREATED_FAILED';
export const CHALLENGE_UPDATED = 'CHALLENGE_UPDATED';
export const CHALLENGE_UPDATE_FAILED = 'CHALLENGE_UPDATE_FAILED';
export const CHALLENGE_DELETED = 'CHALLENGE_DELETED';
export const CHALLENGE_DELETE_FAILED = 'CHALLENGE_DELETE_FAILED';